### PR TITLE
Added video several keyboard responses plugin

### PR DESCRIPTION
**Pull request by marianylund**
Hello, this is still my first time contributing to an open-source project, so I will highly appreciate any feedback! Thank you @jodeleeuw for the suggestion to add a new plugin instead of changing the original [plugin-video-keyboard-response](https://www.jspsych.org/latest/plugins/video-keyboard-response).

Currently the jsPsych [plugin-video-keyboard-response](https://www.jspsych.org/latest/plugins/video-keyboard-response) plugin records only one response and saves response time information and which key was pressed. I need to be able to play a video and record several inputs while user is watching the video and map it to the current time of the video to know when during the video user responded.

My plan was to continue with a very simple change on top of the existing plugin, so in the future it will be easier to merge. So, I´ve added a new boolean `multiple_responses_allowed` to control if only one response or multiple will be recorded (default true). Also added `video_time` to the data that is returned from the trial.

### CODE REVIEW

**Comment by Shaobin-Jiang** [comment]
The test result made it quite clear:

```
FAIL plugin-video-several-keyboard-responses packages/plugin-video-several-keyboard-responses/src/index.spec.ts
  ● video-several-keyboard-responses simulation › visual mode works

    expect(received).toBeGreaterThan(expected)

    Matcher error: received value must be a number or bigint

    Received has type:  array
    Received has value: [560]

      72 |     await expectFinished();
      [73](https://github.com/jspsych/jspsych-contrib/actions/runs/7180394352/job/19558500296?pr=83#step:7:74) |
    > [74](https://github.com/jspsych/jspsych-contrib/actions/runs/7180394352/job/19558500296?pr=83#step:7:75) |     expect(getData().values()[0].rt).toBeGreaterThan(0);
         |                                      ^
      [75](https://github.com/jspsych/jspsych-contrib/actions/runs/7180394352/job/19558500296?pr=83#step:7:76) |     expect(typeof getData().values()[0].response).toBe("string");
      [76](https://github.com/jspsych/jspsych-contrib/actions/runs/7180394352/job/19558500296?pr=83#step:7:77) |   });
      [77](https://github.com/jspsych/jspsych-contrib/actions/runs/7180394352/job/19558500296?pr=83#step:7:78) | });

      at Object.<anonymous> (src/index.spec.ts:74:38)
```

The original plugin used this line:

```typescript
expect(getData().values()[0].rt).toBeGreaterThan(0);
```

Because the rt it records is a numeric value and since `toBeGreaterThan` expects a number or bigint, it worked fine. With your modified version, what is recorded is an **array** of rt, which is why the error thrown includes:

```
Matcher error: received value must be a number or bigint

    Received has type:  array
    Received has value: [560]
```

You should probably modify this part of the test to loop through the array or check upon the first element of the array or something of the sort.

**Comment by marianylund** [comment]
Thank you so much, [Shaobin-Jiang](https://github.com/Shaobin-Jiang), I think I was able to fix it now

**Comment by bjoluc** [comment]
Good job on blaming the build failure on the dependencies @marianylund! `@jspsych/config` version 2 doesn't work with outdated Node.js versions and the CI for this repo still uses Node.js 14 and 16 instead of 18 and 20. Sorry for this – I'll update the CI config.

**Comment by jodeleeuw** [comment]
@bjoluc can you peek at this when you get the chance? downgrading jspsych-config seems like it made a difference. guessing we should try to resolve this another way?

**Comment by jodeleeuw** [comment]
@bjoluc great timing 😁  thanks!!

**Comment by bjoluc** [comment]
All set on the `main` branch – @marianylund can you merge the `jspsych-contrib/main` branch into your fork's main branch and revert commit 614c0ea? The CI in this PR should still be passing then with the new package versions.

**Comment by marianylund** [comment]
@bjoluc Thank you, I have updated the fork and reverted the commit. Is there anything else I should do?

**Comment by jodeleeuw** [comment]
Nope, looks good to go! Thank you again!

**Pull request merged**
