### PR TITLE
Self paced reading

### PR DESCRIPTION
**Pull request by igmmgi**
Initial commit for 7.0.0

### CODE REVIEW

**Comment by bjoluc** [comment]
> I have to admit that I have no idea what I am doing regarding the index.spec.ts file and just copied it from the template folder, with only minimal changes.

That's no problem at all. We don't require contributions to have automated tests, but we are happy if they have some. If you're interested in providing some tests, the [Jest docs](https://jestjs.io/docs/using-matchers) and any plugin test files (*.spec.ts) in the core repository may be a good starting point. You can run your tests locally via `npm run test` (or `npm run test:watch`).

**Comment by igmmgi** [comment]
I think this is now worth a look. Happy to make changes/fixes!

**Comment by bjoluc** [comment]
@igmmgi Anything blocking this from being released?

**Comment by jodeleeuw** [comment]
This looks good to me. I'm going to release it.

**Pull request merged**
