### PR TITLE
Adding button_response value to trial data

### PR DESCRIPTION
**Pull request by KruttikaBhat**
Bug fix: Added the button_response to trial data. Forgot this in earlier commit.

### CODE REVIEW

**Comment by KruttikaBhat** [comment]
Changed to WIP. Please hold off on merging for now.

**Comment by KruttikaBhat** [comment]
Thanks for waiting on this. We finished the changes and this is ready to be merged. Additional changes include adding the 'responded' css class to the button response and disabling buttons after response across all response modalities.

**Comment by jodeleeuw** [comment]
Can you update the changeset file to reflect the full set of changes? Thanks!

**Comment by KruttikaBhat** [comment]
I updated the changeset file, please let me know if anything else is required, thank you!

**Comment by jodeleeuw** [comment]
I think this should be a minor update instead of a patch update in the changeset file due to the addition of the new feature. Otherwise looks good to me!

**Comment by KruttikaBhat** [comment]
I think the change isn't big enough for being a minor update because the additional feature 'responded' class already existed for the stimulus. Due to the minor update of adding the button response modality, we wanted to also add this for the buttons.

**Pull request merged**
