### PR TITLE
Updates to the plugin by Yu Hei Shum

### PR DESCRIPTION
**Pull request by kinleyid**
Hi @bjoluc, sorry for the difficulty with the last pull request. I've done what you suggested and completely updated my version of jspsych-contrib before adding my updates to this plugin. Hopefully this makes things easier on your end, but please let me know if there's anything else I can do.

### CODE REVIEW

**Comment by bjoluc** [comment]
Thanks @kinleyid! Last but not least, you could add a changeset by following the "Click here if you're a maintainer who wants to add a changeset to this PR" link in the changeset-bot message above, where you replace `patch` with `major` ([semantic versioning](https://semver.org/); will result in v2 being published) and briefly describe the changes. What you write there will be included in the changelog and release notes of your package.
Also, for future PRs, In order to avoid problems like in the previous PR, make sure to push your changes to a separate branch (other than `kinleyid:main`). You can delete that branch then when a PR is merged and pull `jspsych:main` => `kinleyid:main` to get the changes into your repo. This way, `kinleyid:main` can stay up to date with `jspsych:main`...

**Comment by kinleyid** [comment]
Hi @bjoluc, I've just added a changeset (I replaced `patch` with `minor`, since the change is backwards combatable). Thanks very much for the advice, I'll be sure to do that next time I need to make a pull request.

**Comment by bjoluc** [comment]
Oh, sorry, I misread the diff thinking a param was renamed :roll_eyes: Thanks! Note that what you write in the changeset is also what's going to be in the [changelog](https://github.com/jspsych/jspsych-contrib/blob/main/packages/plugin-libet-intentional-binding/CHANGELOG.md) and the GitHub release message. Of course, it's totally up to you how much detail you add there, but I think a few words about what actually changed would help me as a user.

**Comment by kinleyid** [comment]
Hi @bjoluc, I've just updated the changeset to add some more detail! Hopefully this makes it clearer what's being changed.

**Pull request merged**
