### PR TITLE
Added copying task as package

### PR DESCRIPTION
**Pull request by Andre3582**
Here I want to share a plugin I developed to run a copying task. It works with jsPsych version 7.3.0. 
Link: [https://github.com/Andre3582/ext-jspsych-copying-task](https://github.com/Andre3582/ext-jspsych-copying-task)

The basic idea can be seen below:

Copying Task Instructions

The example grid on the left must be recreated in the middle grid. This can be done by dragging and dropping items from the rightmost grid.

This plugin allows you to:
- specify the grid dimensions & sizes
- use provided 'nonsense' shapes or add your own stimuli
- a lot more flexibility

### CODE REVIEW

**Comment by jodeleeuw** [comment]
Thanks @Andre3582! Excited to add this to the repository.

It looks like the docs for the rok plugin got modified by this PR. Can you remove those changes?

I don't have time for a review right now but I'll get to it as soon as I can, or perhaps @bjoluc will beat me to it 😁

**Comment by bjoluc** [comment]
Looks good :+1: I found more joy in performing the example tasks than I'd like to admit :laughing: 

> Any comments/tips are very much appreciated! :)

@Andre3582 If you'd like to avoid having to include `fabric` in a separate script tag – and get some type hints for fabric functions – you might consider migrating to the [TypeScript template](https://github.com/jspsych/jspsych-contrib/tree/main/packages/plugin-template-ts) (development setup instructions [here](https://www.jspsych.org/7.3/developers/configuration/)). This would also allow the plugin to be used as a JavaScript (ES) module. The build chain could bundle `fabric` along with the plugin into the generated `index.browser.min.js` file. Happy to assist if you're interested. Otherwise, I'll happily merge this!

**Comment by Andre3582** [comment]
Hey @bjoluc,
Awesome, thanks for going through the package! 

Migrating to TypeScript sounds neat, but to be honest I don't have much time anytime soon to work on this myself. 

I would suggest merging plugin as it is now. Perhaps some time in the near future I'll ask you for some assistance to do this ;)

PS: If migrating is something that can be done without me, I totally give all permissions to do so.

**Comment by bjoluc** [comment]
Merging this for now then :slightly_smiling_face:

**Pull request merged**
