### PR TITLE
added mixed mode to show stimuli of layers mixed instead of layered o…

### PR DESCRIPTION
**Pull request by younesStrittmatter**
…ntop of each other

### CODE REVIEW

**Comment by jodeleeuw** [comment]
Hi @younesStrittmatter 

Can you add a change set that documents the update and indicates whether this is a minor or major release?

**Comment by jodeleeuw** [comment]
@younesStrittmatter Am I understanding correctly that the `aperture_draw_mode` parameter's default setting changes the default behavior of the plugin because the new option is used as the default? If so, this probably should be flagged as a major release. Minor releases can add new features but shouldn't change the behavior of a script written with the previous version.

**Comment by younesStrittmatter** [comment]
No I did it the other way arround. The default behaviour is the same. If one wants the new behaviour one must specify the new option. Old scripts should work exactly the same as they were before.

**Comment by jodeleeuw** [comment]
My bad! I thought `overlay` mode was the new mode.

**Pull request merged**
