### PR TITLE
Add html-multi-response plugin

### PR DESCRIPTION
**Pull request by richford**
This plugin displays HTML content and records responses generated by **both** button click and the keyboard. Allowing multiple response modalities is useful when designing assessments that will be administered on both desktop and mobile (e.g., phone or tablet) devices.

### CODE REVIEW

**Comment by jodeleeuw** [comment]
Thanks @richford, this looks great!

**Comment by richford** [comment]
Thanks @jodeleeuw for the rapid response! I had one question about the release workflow. GitHub actions seems to indicate that the release action was cancelled. Is there any way we could restart it. I'm asking because we'd like to `npm install` this plugin from the jspsych-contrib organization.

Thanks for all of your hard work in maintaining jspsych!

**Comment by jodeleeuw** [comment]
There was a GitHub-wide outage on Actions right when this action was trying to run, and it has created some lingering problems that mean I can't rerun it. I've been in touch with GH support about it. Hoping I can trigger the actions again soon. I'll give it a shot and see if it is resolved.

**Comment by jodeleeuw** [comment]
@bjoluc do you have any ideas about how to run these actions again without *re*running the same job? Support says that we can't rerun the existing jobs, but there's no manual trigger for these actions.

**Comment by bjoluc** [comment]
> @bjoluc do you have any ideas about how to run these actions again without _re_running the same job? Support says that we can't rerun the existing jobs, but there's no manual trigger for these actions.

Yup, 9cb7330 :stuck_out_tongue: I just noticed the `private` flag in `package.json` and removed it along with the package-level package-lock.json, giving GitHub another shot...

**Comment by jodeleeuw** [comment]
Ah, good catch. Thank you! 👍

**Comment by bjoluc** [comment]
Just updated the deps in package-lock.json for the first time since I fixed the Babel build in @jspsych/config (somehow forgot to do that before). Version 1.0.0 of this package didn't run through Babel yet. Sorry for that if it matters to you @richford! Every release from now on will.

**Comment by richford** [comment]
Thanks @jodeleeuw and @bjoluc !

**Pull request merged**
