### PR TITLE
fixed bug in mixed layering mode

### PR DESCRIPTION
**Pull request by younesStrittmatter**
Sorry, there was a bug in the last commit someone else found.

### CODE REVIEW

**Comment by jodeleeuw** [comment]
Should this be a `patch` bump instead of a `minor` bump?

**Comment by younesStrittmatter** [comment]
Yes, I think a patch would make more sense.

**Comment by younesStrittmatter** [comment]
How should I change the commit for it to be a patch? Delete the changeset?

**Comment by bjoluc** [comment]
@younesStrittmatter You can edit `.changeset/rotten-geckos-switch.md` and replace `minor` with `patch` :tada:

**Comment by younesStrittmatter** [comment]
@jodeleeuw and @bjoluc: Thank you alot. I changed it to be a patch

**Pull request merged**
