### PR TITLE
BF: Fix simulation mode for plugin-html-multi-response

### PR DESCRIPTION
**Pull request by richford**
This PR fixes a bug in the visual simulation mode of the HTML Multi Response plugin.

The old version flipped a coin to determine whether the simulated data was from a button press or a key press and then flipped another independent coin to determine how to interact visually. That was incorrect. This PR implements a bug fix where the visual mode depends directly on the simulated data.

### CODE REVIEW

**Comment by richford** [comment]
Tagging @AnyaWMa and @jyeatman for visibility.

**Comment by jodeleeuw** [comment]
Thanks @richford! The bump to version 1.0.1 will be done automatically by the changeset merge, so that change can be reverted.

**Comment by richford** [comment]
Thanks @jodeleeuw! I reverted the version bump in the latest two commits.

**Comment by richford** [comment]
Sure thing! I did that in the latest commit.

**Pull request merged**
